#!/bin/sh
# --- SDE-COPYRIGHT-NOTE-BEGIN ---
# This copyright note is auto-generated by ./scripts/Create-CopyPatch.
#
# Filename: target/sheba/pkgs/util-vserver/etc_init.d_vserver.sh
# Copyright (C) 2008 The OpenSDE Project
#
# More information can be found in the files COPYING and README.
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 of the License. A copy of the
# GNU General Public License can be found in the file COPYING.
# --- SDE-COPYRIGHT-NOTE-END ---

case "$1" in
start)
	# FIXME: var/run gets wiped out on each boot, the directories should be preserved
	mkdir -p /var/run/vservers{,.rev}
	mkdir -p /var/run/vshelper

	sysctl kernel.vshelper=D_libdir/util-vserver/vshelper
	;;
esac
